[package]
name = "v4l2-gui"
version = "0.1.0"
edition = "2021"

[dependencies]
adw = { version = "0.7.0", package = "libadwaita", features = ["v1_5"] }
glib = "0.20.0"
gtk = { version = "0.9.0", package = "gtk4", features = ["v4_14"] }
tempfile = "3.10.1"
v4l = "0.14.0"
